apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-mcgm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-mcgm
    app.kubernetes.io/part-of: test-annotations-app-ygmu
  name: test-annotations-mcgm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-mcgm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-mcgm
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-kvfd-tenant/test-annotations-app-ygmu/test-annotations-mcgm@sha256:6e1f4c0006e8c14aa91d52e9ef968ffce62200e1647305a5ac67feb40162beeb
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
